version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "cap"
    ports:
      - "15432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data 
    networks:
      - workshop1-network
      
  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "cap@zrp.com.br"
      PGADMIN_DEFAULT_PASSWORD: "cap"
    ports:
      - "10080:80"
    depends_on:
      - db
    networks:
      - workshop1-network

networks: 
  workshop1-network:
    driver: bridge
